sudo: required
services:
  -docker
  
before_install:
  - docker build -t dmytroz/react-test2 -f ./client/Dockerfile.dev ./client
  
script:
   - docker run -e CI=true dmytroz/react-test2 npm test -- --coverage
   #123
after_success:
   - docker build -t dmytroz/multi-client ./client 
   - docker build -t dmytroz/multi-ngnix ./ngnix 
   - docker build -t dmytroz/multi-server ./server
   - docker build -t dmytroz/multi-worker ./worker
   
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push dmytroz/multi-client
   - docker push dmytroz/multi-ngnix
   - docker push dmytroz/multi-server
   - docker push dmytroz/multi-worker