sudo: required
services:
  -docker
  
before_install:
  - docker build -t dmytroz/react-test2 -f ./client/Dockerfile.dev ./client
  
script:
   - docker run -e CI=true dmytroz/react-test2 npm test -- --coverage
   #123
after_success:
   - docker build -t vinfreeman/multi-client ./client 
   - docker build -t vinfreeman/multi-nginx ./nginx 
   - docker build -t vinfreeman/multi-server ./server
   - docker build -t vinfreeman/multi-worker ./worker
   
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   
   - docker push vinfreeman/multi-client
   - docker push vinfreeman/multi-nginx
   - docker push vinfreeman/multi-server
   - docker push vinfreeman/multi-worker
   
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-744413631919"
    bucket_path: "docker-multi"
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"